import type {
  AssistanceRequest,
  MedicalCaseAssistanceRequest,
  TransportAssistanceRequest,
} from "@/types/assistance-request";

const now = new Date();
const iso = (d: Date) => d.toISOString();
const daysAgo = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000);

export const dummyTransportRequests: TransportAssistanceRequest[] = [
  {
    id: "dummy-transport-1",
    requestNumber: "TR-2025-001",
    type: "transport",
    status: "confirmed",
    threadIds: ["thread-t1"],
    linkedThreads: [{ threadId: "thread-t1", subject: "Transport TR-2025-001", latestDate: iso(daysAgo(2)) }],
    createdAt: iso(daysAgo(2)),
    updatedAt: iso(daysAgo(0)),
    receivedAt: iso(daysAgo(2)),
    caseProviderId: null,
    insuranceCompanyReferenceNumber: "INS-REF-4401",
    patient: {
      patientName: "Ahmed Hassan",
      patientBirthdate: "1985-03-12",
      patientNationality: "Egyptian",
    },
    diagnosis: "Post-surgery transfer",
    notes: "Wheelchair accessible vehicle required.",
    pickupPoint: "Cairo University Hospital, Main Entrance",
    dropOffPoint: "15 El Nasr St., Maadi, Cairo",
    dateOfRequestedTransportation: iso(daysAgo(1)),
    estimatedPickupTime: iso(daysAgo(1)),
    estimatedDropOffTime: iso(daysAgo(1)),
    modeOfTransportation: "als",
    withEscortingMedicalCrew: true,
    hasCompanion: true,
  },
  {
    id: "dummy-transport-2",
    requestNumber: "TR-2025-002",
    type: "transport",
    status: "pending",
    threadIds: [],
    linkedThreads: [],
    createdAt: iso(daysAgo(1)),
    updatedAt: iso(daysAgo(0)),
    receivedAt: iso(daysAgo(1)),
    caseProviderId: null,
    insuranceCompanyReferenceNumber: "INS-REF-4402",
    patient: {
      patientName: "Sara Mohamed",
      patientBirthdate: "1992-07-08",
      patientNationality: "Egyptian",
    },
    diagnosis: "Routine dialysis",
    notes: null,
    pickupPoint: "Home - 22 Mokattam Hills, Cairo",
    dropOffPoint: "Dar Al Fouad Hospital, 6th October",
    dateOfRequestedTransportation: iso(now),
    estimatedPickupTime: null,
    estimatedDropOffTime: null,
    modeOfTransportation: "bls",
    withEscortingMedicalCrew: false,
    hasCompanion: false,
  },
  {
    id: "dummy-transport-3",
    requestNumber: "TR-2025-003",
    type: "transport",
    status: "completed",
    threadIds: ["thread-t3"],
    linkedThreads: [{ threadId: "thread-t3", subject: "Transport TR-2025-003", latestDate: iso(daysAgo(4)) }],
    createdAt: iso(daysAgo(5)),
    updatedAt: iso(daysAgo(4)),
    receivedAt: iso(daysAgo(5)),
    caseProviderId: null,
    insuranceCompanyReferenceNumber: "INS-REF-4398",
    patient: {
      patientName: "Omar Khalil",
      patientBirthdate: "1978-11-20",
      patientNationality: "Jordanian",
    },
    diagnosis: "Discharge to residence",
    notes: "Lemozen preferred.",
    pickupPoint: "Saudi German Hospital, Cairo",
    dropOffPoint: "Heliopolis, 12 Baghdad St.",
    dateOfRequestedTransportation: iso(daysAgo(4)),
    estimatedPickupTime: iso(daysAgo(4)),
    estimatedDropOffTime: iso(daysAgo(4)),
    modeOfTransportation: "lemozen",
    withEscortingMedicalCrew: true,
    hasCompanion: true,
  },
];

export const dummyMedicalCaseRequests: MedicalCaseAssistanceRequest[] = [
  {
    id: "dummy-medical-1",
    requestNumber: "MC-2025-001",
    type: "medical_case",
    status: "gop_sent",
    threadIds: ["thread-m1"],
    linkedThreads: [{ threadId: "thread-m1", subject: "Medical case MC-2025-001", latestDate: iso(daysAgo(3)) }],
    createdAt: iso(daysAgo(3)),
    updatedAt: iso(daysAgo(0)),
    receivedAt: iso(daysAgo(3)),
    caseProviderId: null,
    insuranceCompanyReferenceNumber: "BIA-2025-001",
    patient: {
      patientName: "Fatma Ibrahim",
      patientBirthdate: "1990-01-15",
      patientNationality: "Egyptian",
    },
    diagnosis: "Appendectomy - uncomplicated",
    notes: "GOP sent to case provider. Awaiting approval.",
    caseProviderReferenceNumber: "CP-REF-3301",
    admissionDate: iso(daysAgo(4)),
    dischargeDate: iso(daysAgo(2)),
    country: "Egypt",
    city: "Cairo",
    medicalProviderId: null,
    medicalProviderName: "Dar Al Fouad Hospital",
    motherInsuranceCompany: "Allianz Egypt",
  },
  {
    id: "dummy-medical-2",
    requestNumber: "MC-2025-002",
    type: "medical_case",
    status: "investigation",
    threadIds: [],
    linkedThreads: [],
    createdAt: iso(daysAgo(1)),
    updatedAt: iso(daysAgo(0)),
    receivedAt: iso(daysAgo(1)),
    caseProviderId: null,
    insuranceCompanyReferenceNumber: "BIA-2025-002",
    patient: {
      patientName: "Youssef Ali",
      patientBirthdate: "1982-09-22",
      patientNationality: "Egyptian",
    },
    diagnosis: "Cardiac catheterization - pending review",
    notes: "Additional documents requested by insurer.",
    caseProviderReferenceNumber: null,
    admissionDate: iso(daysAgo(1)),
    dischargeDate: null,
    country: "Egypt",
    city: "Giza",
    medicalProviderId: null,
    medicalProviderName: "Cairo University Hospitals",
    motherInsuranceCompany: "MetLife Egypt",
  },
  {
    id: "dummy-medical-3",
    requestNumber: "MC-2025-003",
    type: "medical_case",
    status: "done",
    threadIds: ["thread-m3"],
    linkedThreads: [{ threadId: "thread-m3", subject: "Medical case MC-2025-003", latestDate: iso(daysAgo(8)) }],
    createdAt: iso(daysAgo(10)),
    updatedAt: iso(daysAgo(8)),
    receivedAt: iso(daysAgo(10)),
    caseProviderId: null,
    insuranceCompanyReferenceNumber: "BIA-2024-089",
    patient: {
      patientName: "Layla Mahmoud",
      patientBirthdate: "1975-04-05",
      patientNationality: "Egyptian",
    },
    diagnosis: "Knee replacement - completed",
    notes: null,
    caseProviderReferenceNumber: "CP-REF-3280",
    admissionDate: iso(daysAgo(12)),
    dischargeDate: iso(daysAgo(8)),
    country: "Egypt",
    city: "Alexandria",
    medicalProviderId: null,
    medicalProviderName: "Alexandria Main University Hospital",
    motherInsuranceCompany: "AXA Egypt",
  },
];

export const dummyAssistanceRequests: AssistanceRequest[] = [
  ...dummyTransportRequests,
  ...dummyMedicalCaseRequests,
];
